export const CANDIDATES = {
  TITLE: 'Candidates',
  FULLNAME: 'Full Name',
  POSITION: 'Position',
  LEVEL: 'Level',
  LOCATION: 'Location',
};

export const EMPLOYEES = {
  TITLE: 'Employees',
  FULLNAME: 'Full Name',
  POSITION: 'Position',
  LEVEL: 'Level',
  LOCATION: 'Location',
};

export const SOFT_SKILL_INTERVIEW = {
  SAVE: 'Save',
  SAVE_CHANGES: 'Save changes',
  START_EDIT: 'Edit soft skills',
  DISABLE_EDIT: 'Disable edit soft skill',
  LEVEL_PLACEHOLDER: 'Choose level',
  POSITION_PLACEHOLDER: 'Choose position',
  NEW_SKILL: 'Add new soft skill',
};

export const GENERATE_CV = 'Generate CV';

// Info source: https://www.loc.gov/standards/iso639-2/php/code_list.php
export const Languages: Record<string, string> = {
  aa: 'Afar',
  ab: 'Abkhazian',
  af: 'Afrikaans',
  ak: 'Akan',
  sq: 'Albanian',
  am: 'Amharic',
  ar: 'Arabic',
  an: 'Aragonese',
  hy: 'Armenian',
  as: 'Assamese',
  av: 'Avaric',
  ae: 'Avestan',
  ay: 'Aymara',
  az: 'Azerbaijani',
  ba: 'Bashkir',
  bm: 'Bambara',
  eu: 'Basque',
  be: 'Belarusian',
  bn: 'Bengali',
  bh: 'Bihari languages',
  bi: 'Bislama',
  bo: 'Tibetan',
  bs: 'Bosnian',
  br: 'Breton',
  bg: 'Bulgarian',
  my: 'Burmese',
  ca: 'Catalan',
  cs: 'Czech',
  ch: 'Chamorro',
  ce: 'Chechen',
  zh: 'Chinese',
  cu: 'Church Slavic',
  cv: 'Chuvash',
  kw: 'Cornish',
  co: 'Corsican',
  cr: 'Cree',
  cy: 'Welsh',
  da: 'Danish',
  de: 'German',
  dv: 'Maldivian',
  nl: 'Dutch',
  dz: 'Dzongkha',
  el: 'Greek (modern)',
  en: 'English',
  eo: 'Esperanto',
  et: 'Estonian',
  ee: 'Ewe',
  fo: 'Faroese',
  fa: 'Persian',
  fj: 'Fijian',
  fi: 'Finnish',
  fr: 'French',
  fy: 'Western Frisian',
  ff: 'Fulah',
  ka: 'Georgian',
  gd: 'Scottish Gaelic',
  ga: 'Irish',
  gl: 'Galician',
  gv: 'Manx',
  gn: 'Guarani',
  gu: 'Gujarati',
  ht: 'Haitian Creole',
  ha: 'Hausa',
  he: 'Hebrew',
  hz: 'Herero',
  hi: 'Hindi',
  ho: 'Hiri Motu',
  hr: 'Croatian',
  hu: 'Hungarian',
  ig: 'Igbo',
  is: 'Icelandic',
  io: 'Ido',
  ii: 'Sichuan Yi',
  iu: 'Inuktitut',
  id: 'Indonesian',
  ik: 'Inupiaq',
  it: 'Italian',
  jv: 'Javanese',
  ja: 'Japanese',
  kl: 'Greenlandic',
  kn: 'Kannada',
  ks: 'Kashmiri',
  kr: 'Kanuri',
  kk: 'Kazakh',
  km: 'Central Khmer',
  ki: 'Kikuyu',
  rw: 'Kinyarwanda',
  ky: 'Kyrgyz',
  kv: 'Komi',
  kg: 'Kongo',
  ko: 'Korean',
  kj: 'Kuanyama',
  ku: 'Kurdish',
  lo: 'Lao',
  la: 'Latin',
  lv: 'Latvian',
  li: 'Limburgan',
  ln: 'Lingala',
  lt: 'Lithuanian',
  lb: 'Luxembourgish',
  lu: 'Luba-Katanga',
  lg: 'Ganda',
  mk: 'Macedonian',
  mh: 'Marshallese',
  ml: 'Malayalam',
  mi: 'Maori',
  mr: 'Marathi',
  ms: 'Malay',
  mg: 'Malagasy',
  mt: 'Maltese',
  mn: 'Mongolian',
  na: 'Nauru',
  nv: 'Navajo',
  nr: 'South Ndebele',
  nd: 'North Ndebele',
  ng: 'Ndonga',
  ne: 'Nepali',
  nn: 'Nynorsk, Norwegian',
  nb: 'Norwegian Bokmål',
  no: 'Norwegian',
  ny: 'Chichewa',
  oc: 'Occitan (post 1500)',
  oj: 'Ojibwa',
  or: 'Oriya',
  om: 'Oromo',
  os: 'Ossetian',
  pa: 'Panjabi',
  pi: 'Pali',
  pl: 'Polish',
  pt: 'Portuguese',
  ps: 'Pushto',
  qu: 'Quechua',
  rm: 'Romansh',
  ro: 'Romanian',
  rn: 'Rundi',
  ru: 'Russian',
  sg: 'Sango',
  sa: 'Sanskrit',
  si: 'Sinhala',
  sk: 'Slovak',
  sl: 'Slovenian',
  se: 'Northern Sami',
  sm: 'Samoan',
  sn: 'Shona',
  sd: 'Sindhi',
  so: 'Somali',
  st: 'Sotho, Southern',
  es: 'Spanish',
  sc: 'Sardinian',
  sr: 'Serbian',
  ss: 'Swati',
  su: 'Sundanese',
  sw: 'Swahili',
  sv: 'Swedish',
  ty: 'Tahitian',
  ta: 'Tamil',
  tt: 'Tatar',
  te: 'Telugu',
  tg: 'Tajik',
  tl: 'Tagalog',
  th: 'Thai',
  ti: 'Tigrinya',
  to: 'Tonga (Tonga Islands)',
  tn: 'Tswana',
  ts: 'Tsonga',
  tk: 'Turkmen',
  tr: 'Turkish',
  tw: 'Twi',
  ug: 'Uyghur',
  uk: 'Ukrainian',
  ur: 'Urdu',
  uz: 'Uzbek',
  ve: 'Venda',
  vi: 'Vietnamese',
  vo: 'Volapük',
  wa: 'Walloon',
  wo: 'Wolof',
  xh: 'Xhosa',
  yi: 'Yiddish',
  yo: 'Yoruba',
  za: 'Zhuang',
  zu: 'Zulu',
};

export const LanguageLevels: Record<string, string> = {
  beginner: 'A1',
  basic: 'A1',
  elementary: 'A2',
  intermediate: 'B1',
  'upper intermediate': 'B2',
  advanced: 'C1',
  proficiency: 'C2',
  native: 'C2',
};
